Adarsh_Ovhal_99 & 119
Apnasite/visiting-card-assignments pull request #47
Opened 2024-09-18 10:59 UTC by Adarshovhal

2024-09-18 17:25 UTC, KalpeshApnasite requested changes

2024-09-18 17:25 UTC, KalpeshApnasite commented on SubmittedAssignments/Adarsh_Ovhal_119/css/style.css
> +    margin-left: 23px;
do not use px unit

2024-09-18 17:25 UTC, KalpeshApnasite commented on SubmittedAssignments/Adarsh_Ovhal_119/css/style.css
> +    left: -60px;
do not use px unit

2024-09-18 17:25 UTC, KalpeshApnasite commented on SubmittedAssignments/Adarsh_Ovhal_119/css/style.css
> +    left: 73px;
do not use px unit

2024-09-20 06:56 UTC, Adarshovhal commented on SubmittedAssignments/Adarsh_Ovhal_119/css/style.css
> +    left: -60px;
updated

2024-09-20 06:57 UTC, Adarshovhal commented on SubmittedAssignments/Adarsh_Ovhal_119/css/style.css
> +    left: 73px;
updated

2024-09-21 05:24 UTC, KalpeshApnasite requested changes
use external css

2024-09-28 08:37 UTC, closed without merging